---
  name: build all
  on:
    push:
      branches:
        - main
  jobs:
    docker:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: setup qemu
          uses: docker/setup-qemu-action@v3.2.0

        - name: setup buildx
          uses: docker/setup-buildx-action@v3.8.0

        - name: login to docker hub
          uses: docker/login-action@v3.3.0
          with:
            registry: docker.io
            username: shinomineko
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: login to ghcr
          uses: docker/login-action@v3.3.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: bake
          uses: docker/bake-action@v5.11.0
          with:
            push: true
            set: |
              *.labels.org.opencontainers.image.revision=${{ github.sha }}
